version: '3.8'

services:
  spring-app:
    build:
      context: ./backend/flight_search_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  web:
    build:
      context: ./frontend/flight_search
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
